using System;
using System.Linq;
using System.Text.Json.Serialization;

namespace Game_Catalog.Models
{
    /// <summary> Represents a video game in the user's catalog. </summary>
    public class Game
    {
        /// <summary> Unique identifier for the game. Generated by the database. </summary>
        public int Id { get; set; }

        private string _title = string.Empty;
        /// <summary> Title of the video game. </summary>
        public string Title
        {
            get => _title;
            set => _title = value ?? string.Empty;
        }

        /// <summary> Identifier of the developer studio, used for persistence. </summary>
        public int DeveloperId { get; set; }

        /// <summary> Reference to the developer studio. </summary>
        public Studio? Developer { get; set; }

        /// <summary> Identifier of the base game, if this game is a DLC. Null for standalone games. </summary>
        public int? ParentGameId { get; set; }

        private string _genre = string.Empty;
        /// <summary> Genre of the game. </summary>
        public string Genre
        {
            get => _genre;
            set => _genre = value ?? string.Empty;
        }

        private int _releaseYear;
        /// <summary> The year the game was released. </summary>
        public int ReleaseYear
        {
            get => _releaseYear;
            set => _releaseYear = Math.Max(0, value);
        }

        private string _platform = string.Empty;
        /// <summary> The gaming platform (e.g., PC, PlayStation). </summary>
        public string Platform
        {
            get => _platform;
            set => _platform = value ?? string.Empty;
        }

        private double _sizeGB;
        /// <summary> Size of the game on disk in Gigabytes. </summary>
        public double SizeGB
        {
            get => _sizeGB;
            set => _sizeGB = Math.Max(0, value);
        }

        /// <summary> Current completion status of the game. </summary>
        public GameStatus Status { get; set; } = GameStatus.Planned;

        private double _hoursPlayed;
        /// <summary> Total hours played, computed from this game's finished sessions. </summary>
        public double HoursPlayed => AppData.Instance.Sessions
            .Where(s => s.GameId == Id && s.Duration.HasValue)
            .Sum(s => s.Duration!.Value.TotalHours);

        private int _personalRating = 5;
        /// <summary> Personal rating given by the user (1 to 10). </summary>
        public int PersonalRating
        {
            get => _personalRating;
            set => _personalRating = Math.Clamp(value, 1, 10);
        }

        private string _description = string.Empty;
        /// <summary> Short description of the game fetched from RAWG. </summary>
        public string Description
        {
            get => _description;
            set => _description = value ?? string.Empty;
        }

        private string _coverImagePath = string.Empty;
        /// <summary> Local file path to the downloaded cover image. </summary>
        public string CoverImagePath
        {
            get => _coverImagePath;
            set => _coverImagePath = value ?? string.Empty;
        }

        private string _executablePath = string.Empty;
        /// <summary> Local file path to the game's executable, used for future auto-tracking of play sessions. </summary>
        public string ExecutablePath
        {
            get => _executablePath;
            set => _executablePath = value ?? string.Empty;
        }

        private string _iconPath = string.Empty;
        /// <summary> Local file path to a small (32x32) icon, used for compact/table display. </summary>
        public string IconPath
        {
            get => _iconPath;
            set => _iconPath = value ?? string.Empty;
        }

        /// <summary> Date and time the game was added to the library. </summary>
        public DateTime AddedAt { get; set; } = DateTime.Now;

        /// <summary> Whether the user has archived this game. </summary>
        public bool IsArchived { get; set; }

        /// <summary> Creates a shallow copy of the game (candidate for saving). </summary>
        public Game Clone() => (Game)MemberwiseClone();

        /// <summary> Applies the properties of another game to this game. </summary>
        public void ApplyFrom(Game other)
        {
            Title = other.Title;
            Developer = other.Developer;
            DeveloperId = other.DeveloperId;
            Genre = other.Genre;
            ReleaseYear = other.ReleaseYear;
            Platform = other.Platform;
            SizeGB = other.SizeGB;
            Status = other.Status;
            PersonalRating = other.PersonalRating;
            Description = other.Description;
            CoverImagePath = other.CoverImagePath;
            IconPath = other.IconPath;
        }
    }
}