using System;
using System.Text.Json.Serialization;

namespace Game_Catalog.Models
{
    /// <summary> Represents a single continuous play session for a game. </summary>
    public class PlaySession
    {
        /// <summary> Unique identifier for the play session. Generated by the database. </summary>
        public int Id { get; set; }

        /// <summary> Identifier of the game this session belongs to, used for persistence. </summary>
        public int GameId { get; set; }

        /// <summary> Reference to the game this session belongs to. Excluded from JSON serialization. </summary>
        [JsonIgnore]
        public Game? Game { get; set; }

        /// <summary> Time the session started. </summary>
        public DateTime StartTime { get; set; }

        /// <summary> Time the session ended. Null if the session is still ongoing. </summary>
        public DateTime? EndTime { get; set; }

        /// <summary> Session duration. Null if the session is still ongoing. </summary>
        public TimeSpan? Duration => EndTime.HasValue ? EndTime.Value - StartTime : null;

        /// <summary> How this session record was added — manually or detected automatically. </summary>
        public EntryMethod EntryMethod { get; set; } = EntryMethod.Manual;

        private string _note = string.Empty;
        /// <summary> Optional free-text note about the session. </summary>
        public string Note
        {
            get => _note;
            set => _note = value ?? string.Empty;
        }
    }
}